[project]
name = "setzy-agent"
version = "1.0.0"
description = "A setzy agent."
authors = [
    {name = "KoltonStarr",email = "carnegieroyce@protonmail.com"}
]
readme = "README.md"
requires-python = ">=3.12,<3.14"
dependencies = [
    "langchain (>=1.2.0,<2.0.0)",
    "langchain-openai (>=1.1.6,<2.0.0)",
    "langchain-chroma (>=1.1.0,<2.0.0)",
    "langchain-community (>=0.4.1,<0.5.0)",
    "chromadb (>=1.4.0,<2.0.0)",
    "python-dotenv (>=1.2.1,<2.0.0)",
    "ddgs (>=9.10.0,<10.0.0)",
    "fastapi[standard] (>=0.128.0,<0.129.0)"
]

[tool.poetry]
package-mode = false

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
