[project]
name = "setzy-client"
version = "0.1.0"
description = ""
authors = [
    {name = "KoltonStarr",email = "carnegieroyce@protonmail.com"}
]
readme = "README.md"
requires-python = ">=3.12,<3.14"
dependencies = [
    "typer (>=0.24.1,<0.25.0)"
]

[tool.poetry]
package-mode = false

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
